AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Capture the Public IP Address during Lambda execution for CloudTrail correlation

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: getpublicip
      Description: Capture the Public IP Address during Lambda execution for CloudTrail correlation
      ContentUri: s3://getpublicip-us-east-2/extension.zip
      CompatibleRuntimes:
        - python3.7
        - python3.8
        - python3.9
        - python3.10
        - python3.11
      CompatibleArchitectures:
        - arm64
        - x86_64
      LicenseInfo: Apache-2.0
      RetentionPolicy: Retain

Outputs:
  LayerArn:
    Value: !Ref SharedLayer
